### ISSUE TITLE
breaks mithrix (mithrix doesnt spawn)

### ISSUE THREAD

**Issue by ReiTheTrap** [prodzpod/RecoveredAndReformed#2]
mithrix didnt spawned when this mod was in modpack
[zipped_log.zip](https://github.com/user-attachments/files/16588256/zipped_log.zip) (sorry the log is big cuz i never cleaned it. The most recent run is the one where mithrix didnt spawn (we left the game without continuing). It happend 2 times but other time was after many runs ago (we died alot before reaching mithrix).

first try was without the umbralmithrix, 2nd was with it.
i deleted this mod and with debugtoolkit tried to activate mithrix fight once again and it worked.

**Comment by prodzpod** [comment]
all of this should work post sots
